package cc.rits.openhacku2022.db.mapper.base;

import cc.rits.openhacku2022.db.entity.OrderProduct;
import cc.rits.openhacku2022.db.entity.OrderProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface OrderProductBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    long countByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int deleteByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orderId") Integer orderId, @Param("productId") Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int insert(OrderProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int insertSelective(OrderProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    List<OrderProduct> selectByExampleWithRowbounds(OrderProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    List<OrderProduct> selectByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    OrderProduct selectByPrimaryKey(@Param("orderId") Integer orderId, @Param("productId") Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") OrderProduct row, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") OrderProduct row, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderProduct row);
}