package cc.rits.openhacku2022.db.mapper.base;

import cc.rits.openhacku2022.db.entity.OrderMenu;
import cc.rits.openhacku2022.db.entity.OrderMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface OrderMenuBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    long countByExample(OrderMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    int deleteByExample(OrderMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("menuId") Integer menuId, @Param("orderId") Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    int insert(OrderMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    int insertSelective(OrderMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    List<OrderMenu> selectByExampleWithRowbounds(OrderMenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    List<OrderMenu> selectByExample(OrderMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    OrderMenu selectByPrimaryKey(@Param("menuId") Integer menuId, @Param("orderId") Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") OrderMenu row, @Param("example") OrderMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") OrderMenu row, @Param("example") OrderMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderMenu row);
}