package cc.rits.openhacku2022.db.mapper.base;

import cc.rits.openhacku2022.db.entity.Table;
import cc.rits.openhacku2022.db.entity.TableExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TableBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    long countByExample(TableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    int deleteByExample(TableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    int insert(Table row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    int insertSelective(Table row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    List<Table> selectByExampleWithRowbounds(TableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    List<Table> selectByExample(TableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    Table selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Table row, @Param("example") TableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Table row, @Param("example") TableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Table row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Table row);
}