spring:
  datasource:
    url: jdbc:mysql://localhost:3307/openhacku2022?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: openhacku2022
    password: openhacku2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1

gcp:
  project-id: GCP_PROJECT_ID
  credentials-path: GCP_CREDENTIALS_PATH
  cloud-storage:
    enabled: false
    bucket-name: GCP_BUCKET_NAME

stripe:
  checkout:
    enabled: false
    success-url: STRIPE_SUCCESS_URL
    cancel-url: STRIPE_CANCEL_URL
    product-id: STRIPE_PRODUCT_ID
    tax-id: STRIPE_TAX_ID
  secret-key: STRIPE_SECRET_KEY
